create table if not exists public.research_responses (
  id bigint generated by default as identity primary key,
  submission_id uuid not null unique,
  participant_id text not null,
  submitted_at timestamptz not null default now(),
  response_data jsonb not null
);

alter table public.research_responses enable row level security;

revoke all on table public.research_responses from anon, authenticated;
